---
- name: Shutdown Apparmor Services
  service:
    name: apparmor
    state: stopped
    enabled: false
- name: teardown
  command: aa-teardown
- name: Remove Apparmor Packages
  package:
    name: [ apparmor ]
    state: absent
    ignore_errors: yes
- name: remove apparmor-related files or directories
  file:
    path: "{{ item }}"
    state: absent
    loop:
      - /etc/apparmor
      - /etc/apparmor.d
      - /etc/rcS.d/S01apparmor
      - /etc/rcS.d/K01apparmor
      - /etc/init.d/apparmor
      - /usr/lib/apparmor
      - /var/lib/snapd/apparmor
      - /var/cache/apparmor
      - /etc/systemd/system/apparmor.service
