---

- name: Disable SELinux
  selinux:
    state: disabled
  when: ansible_facts['os_family'] == "CentOS"

- name: Unconditionally reboot the machine with all defaults
  reboot:
  when: ansible_facts['os_family'] == "CentOS"
