---
<<<<<<< HEAD

#- name: Add influxdb repo file
#  copy:
#    src: influxdb.repo
#    dest: /etc/yum.repos.d
#    owner: root
#    group: root
#    mode: 0644
#  tags: [ install, influxdb ]
=======
- name: Add influxdb repo file
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  tags: [ install, influxdb ]
>>>>>>> d8b03fd68da72e0462dfc2b88d2ebec86b06f383

- name: Install influx
  package:
    name: influxdb
    # enablerepo: influxdb
    state: present
  notify: influxdb restart
  tags: [ install, influxdb ]

<<<<<<< HEAD
- name: Set admin credentials
  command: influx -username admin -password {{ influxdb_admin_pass }} -execute "CREATE USER admin WITH PASSWORD '{{ influxdb_admin_pass }}' WITH ALL PRIVILEGES" -database internal
  tags: [ configure, influxdb ]
=======
#- name: Set admin credentials
#  shell: influx -execute "CREATE USER admin WITH PASSWORD '{{ influxdb_admin_pass }}' WITH ALL PRIVILEGES"
#  tags: [ configure, influxdb ]
>>>>>>> d8b03fd68da72e0462dfc2b88d2ebec86b06f383

- name: Copy influxdb config file
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  diff: yes
  notify: influxdb restart
  tags: [ configure, influxdb ]

- meta: flush_handlers

- name: Start influxdb
  systemd:
    name: influxdb
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [ install, influxdb ]
