---
- name: Remove Apache2
  apt:
      name: apache2
      state: absent

- name: Install nessesary package
  apt:
      name: apt-transport-https
      state: present
      update_cache: yes

- name: add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: add grafana repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Install grafana
  apt: 
      name: grafana
      state: present
      update_cache: yes

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started

- name: Check if Grafana is accessible
  uri:
    url: http://10.0.0.10:3000
    method: GET
    status_code: 200

- name: Create influxdb datasource
  community.grafana.grafana_datasource:
    name: "datasource-influxdb"
    grafana_url: "https://10.0.0.10"
    grafana_user: "admin"
    grafana_password: "xxxxxx"
    org_id: "1"
    ds_type: "influxdb"
    ds_url: "https://10.0.0.8:3000"
    database: "telegraf"
    time_interval: ">1s"
    tls_ca_cert: "/etc/ssl/certs/ca.pem"