---

- name: Update Servers and Install LAMP
  gather_facts: false
  hosts: clients
  tasks:
   - name: Udate system
     apt: update_cache=yes force_apt_get=yes
   - name: Upgrade system
     apt: upgrade=dist force_apt_get=yes
   - name: Check if a reboot is needed on all servers
     register: reboot_required_file
     stat: path=/var/run/reboot-required get_md5=no

   - name: Reboot the box if kernel updated
     reboot:
      msg: "Reboot initiated by Ansible for kernel updates"
     when: reboot_required_file.stat.exists
   - name: Install Python
     apt: pkg=python3 state=present
   - name: install Apache
     apt: pkg=apache2 state=present
   - name: install PHP
     apt: pkg=php state=present
   - name: install MySql
     apt: pkg=mariadb-server state=present
   - name: install PHPMyadmin
     apt: pkg=phpmyadmin state=present
