---
- hosts: all
  gather_facts: true
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"
  - name: Distribution version
    debug: msg="{{ ansible_distribution_version}}"
  - name: Distribution major version
    debug: msg="{{ ansible_distribution_major_version }}"
  - name: OS family
    debug: msg="{{ ansible_os_family }}"



  - name: Creates Config path directory
    file:
      path:  /root/.config/mc
      state: directory
  - name: Enable Internal MC editor
    ansible.builtin.lineinfile:
      path: /root/.config/mc/ini
      regexp: '^use_internal_edit=false'
      line: 'use_internal_edit=true'

