---
- name: Add Aliases
  blockinfile:
    path: /root/.bashrc
    block: |
       alias ll="ls -alF --time-style=long-iso -r -h"
       alias add="dnf -y install"
       alias update="dnf update && dnf  -y upgrade"
       alias remove="dnf -y remove"
       alias search="dnf search"
       alias tailf="tail -f "
       alias error="tailf /var/log/httpd/error.log"
       alias access="tailf /var/log/httpd/access_log"
       alias work="cd /var/www/html"
       alias ports="netstat -antupl4 | grep LISTEN"


- name: Add Environment Variables that set Internal Editor => Default for Midnight Commander 
  blockinfile:
    path: /root/.profile
    block: |
       EDITOR=mcedit 
       aVISUAL=$EDITOR
       export EDITOR VISUAL


