---

- name: ensure profile file exists
  copy:
    content: ""
    dest: /root/.bash_profile
    force: no
    group: root
    owner: root
    mode: 0555

- name: Add Aliases
  blockinfile:
    path: /root/.bash_profile
    block: |
       force_color_prompt=yes
       PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\] '
       alias ll="ls -alF --time-style=long-iso -r -h --color=auto"
       alias add="apt-get -y -qq install"
       alias update="apt-get update -qq && apt-get -y upgrade -qq && apt-get -qq -y dist-upgrade"
       alias remove="apt-get  -y remove"
       alias purge="apt-get  -y purge"
       alias search="apt-cache search"
       alias policy="apt-cache policy"
       alias tailf="tail -f"
       alias error="tailf /var/log/apache2/error.log"
       alias access="tailf /var/log/apache2/access.log"
       alias ports="netstat -ntupl4"
       alias work="cd /var/www/html"
       alias adres="ip a s | grep inet | grep -v inet6"
       alias d="docker"
       alias dc="docker-compose"

- name: Make Bash Prompt Pretty
  blockinfile:
    path: /root/.bashrc
    block: |
       force_color_prompt=yes
       PS1='\[\033[1;36m\]\u\[\033[1;31m\]@\[\033[1;32m\]\h:\[\033[1;35m\]\w\[\033[1;31m\]\$\[\033[0m\] '