---

- name: ensure profile file exists
  copy:
    content: ""
    dest: /root/.bash_profile
    force: no
    group: root
    owner: root
    mode: 0555

- name: Add Aliases
  blockinfile:
    path: /root/.bash_profile
    block: |
       alias ll="ls -alF --time-style=long-iso -r -h"
       alias add="apt-get -y -qq install"
       alias update="apt-get update -qq && apt-get -y upgrade -qq && apt-get -qq -y dist-upgrade"
       alias remove="apt-get  -y remove"
       alias purge="apt-get  -y purge"
       alias search="apt-cache search"
       alias policy="apt-cache policy"
       alias tailf="tail -f"
       alias error="tailf /var/log/apache2/error.log"
       alias access="tailf /var/log/apache2/access_log"
       alias ports="netstat -ntupl4"
       alias work="cd /var/www/html"
       #alias ports="lsof -i  -P -n"
       alias addresses="ip a s | grep inet | grep -v inet6"
