---
- name: "Create influxdb database {{ influx_database }}"
  local_action:
    module: influxdb_database
    username: "admin"
    password: "{{ influxdb_admin_pass }}"
    ssl: yes
    validate_certs: yes
    database_name: "{{ influx_database }}"
  run_once: true
  tags: [ install ]
- name: "Apply retention policy to {{ influx_database }}"
  local_action:
    module: influxdb_retention_policy
    database_name: "{{ influx_database }}"
    username: "admin"
    password: "{{ influxdb_admin_pass }}"
    ssl: yes
    validate_certs: yes
    policy_name: "{{ influx_retention_policy_name }}"
    default: yes
    duration: "{{ influx_retention_duration }}"
    replication: 1
    shard_group_duration: "{{ influx_shard_duration }}"
  run_once: true
  tags: [ install ]
- name: "Create influxdb user {{ influx_user }}"
  local_action:
    module: influxdb_user
    username: "admin"
    password: "{{ influxdb_admin_pass }}"
    ssl: yes
    validate_certs: yes
    user_name: "{{ influx_user }}"
    user_password: "{{ influx_password }}"
    grants:
      - database: "{{ influx_database }}"
        privilege: 'ALL'
  run_once: true
  tags: [ install ]
