---

- name: Update Debian
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_facts['os_family'] == "Debian"

- name: Upgrade  Debian
  apt:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "Debian"


- name: Update Ubuntu
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_facts['os_family'] == "Ubuntu"

- name: Upgrade  Ubuntu
  apt:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "Ubuntu"


- name: Update RedHat
  yum:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: check if a reboot is required
  shell: "[ -f /var/run/reboot-required ]"
  failed_when: False
  register: reboot_required
  changed_when: reboot_required.rc == 0
  notify: reboot
