---

- name: Update Debian
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  when: ansible_facts['os_family'] == "Debian"

- name: Upgrade  Debian
  apt:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "Debian"


- name: Update RedHat
  yum:
    name: "*"
    state: latest
  when: ansible_facts['os_family'] == "RedHat"
