---
- name: Install Midnight Commander
  apt:
   name: "mc"
   state: latest
  when: ansible_facts['os_family'] == "Debian"

- name:  Make Midnight Commander Exit Same Directory Script
  script: script.sh

- name: Creates Midnight Commander Config path directory
  file:
   path:   /root/.config/mc/
   state: directory
   recurse: yes

- name: Make Midnight Commander internal default Editor

  ansible.builtin.copy:
    src: ini
    dest: /root/.config/mc/
    owner: root
    group: root
    mode: '0644'
