---
- name: Install Midnight Commander
  apt:
   name: "mc"
   state: latest
  when: ansible_facts['os_family'] == "Debian"


- name:  Default MC Editor #1
  blockinfile:
    path: /root/.bash_profile
    create: yes
    block: |
       EDITOR=mcedit
       aVISUAL=$EDITOR
       export EDITOR VISUAL

- name: Default MC Editor #2
  blockinfile:
    path: /root/.profile
    create: yes
    block: |
       EDITOR=mcedit
       aVISUAL=$EDITOR
       export EDITOR VISUAL
- name:  Make Midnight Commander Exit Same Directory Script
  script: script.sh
