---
- name: Install Midnight Commander
  package:
   name: "mc"
   state: latest

#- name: Make Internal Default MC Editor
#  lineinfile:
#    path: /root/.config/mc/ini
#    search_string: 'use_internal_edit=false'
#    line: use_internal_edit=true
#    owner: root
#    group: root
#    mode: '0644'
#    create: yes
