---
- name: Install Midnight Commander
  apt:
    name: "mc"
    state: latest
- name: Create config directory
  file:
    path:  /root/.config/mc
    state: directory
#- name: Create MC config directory
#  file:
#    path:  /root/.config/mc
#    state: directory
- name: Make MC use Internal Editor
  lineinfile:
    path: /root/.config/mc/ini
    search_string: 'use_internal_edit=false'
    line: use_internal_edit=true
    owner: root
    group: root
    mode: '0644'