---
- name: Install Midnight Commander
  package:
   name: "mc"
   state: latest

- name: Set Internal Editor Default Midnight Commander Editor => .bash_profile
  blockinfile:
    path: /root/.bash_profile
    create: yes
    block: |
       EDITOR=mcedit 
       aVISUAL=$EDITOR
       export EDITOR VISUAL

- name: Set Internal Editor Default Midnight Commander Editor => .profile
  blockinfile:
    path: /root/.profile
    create: yes
    block: |
       EDITOR=mcedit 
       aVISUAL=$EDITOR
       export EDITOR VISUAL




- name:  Make Midnight Commander Exit Same Directory Script
  script: script.sh
