---
- name: Set up multiple authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - public.pub
- name: Disable Host Key checking

  ansible.builtin.copy:
    src: config
    dest: /root/.ssh/
    owner: root
    group: root
    mode: '0644'
