---

- name: Set up multiple authorized keys
  authorized_key:
    user: root
    state: present
    key: '{{ item }}'
  with_file:
    - public.pub
- name: Disable Host Key checking

  ansible.builtin.copy:
    src: config
    dest: /root/.ssh/
    owner: root
    group: root
    mode: '0644'
<<<<<<< HEAD
=======
- name: Disable Strict Host Key Chekcing
  copy:
    src: config
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: '0644' 
>>>>>>> 150cabc9816985d3e5dcdb670692a047545fe3d3
