---
- hosts: all
  tasks:
    - name: Update System
    - shell: apt-get update && apt-get -y upgrade && apt-get -y dist-upgrade
    - shell: yum -y upgrade

       - name: 1. install Apache
      apt: name=apache2 state=latest
      yum: name=httpd state=latest

    - name: 2. install PHP
      apt: name=php7.4 state=latest
      yum: name=php7.4 state=latest

    - name: 3. start Apache
      service: name=apache2 state=started enabled=yes
    - name: 4. install PHPMyadmin
      apt: name=phpmyadmin state=latest
      yum: name=phpmyadmin state=latest

    - name: 5. install Hello World PHP script & delete index.html
      copy: src=index.php dest=/var/www/html/index.php mode=0664


    - shell: /bin/rm  /var/www/html/index.html