---

- name: Install Virtual Machine Tools
  apt: name= "{{ item }}" state=latest
  with_items:
  - linux-cloud-tools-virtual
  - linux-tools-virtual
  - linux-virtual
  update_cache: true

- name: Insert module names into Initram list
  blockinfile:
    path: /etc/initramfs-tools/modules
    block: |
      hv_vmbus
      hv_storvsc
      hv_blkvsc
      hv_netvsc
- name: Rebuild InitRam
  command: update-initramfs -u
