---

- name: shutdown services
  service:
    name: apparmor
  when: ansible_os_family == "Debian"

- name: teardown
  command: |
    aa-teardown
  register: teardown
  failed_when: false
  changed_when: false
  when: ansible_os_family == "Debian"

- name: remove apparmor packages
  package:
    name: [ apparmor ]
    state: absent
  when:  ansible_os_family == "Debian"

- name: remove apparmor-related files or directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/apparmor
    - /etc/apparmor.d
    - /etc/rcS.d/S01apparmor
    - /etc/rcS.d/K01apparmor
    - /etc/init.d/apparmor
    - /usr/lib/apparmor
    - /var/lib/snapd/apparmor
    - /var/cache/apparmor
    - /etc/systemd/system/apparmor.service
  when: ansible_os_family == "Debian"
