---
- name: Add influxdb repo file
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  tags: [ install, influxdb ]

- name: Install influx
  package:
    name: influxdb
    enablerepo: influxdb
    state: present
  notify: influxdb restart
  tags: [ install, influxdb ]

#  tags: [ configure, influxdb ]

- name: Copy influxdb config file
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  diff: yes
  notify: influxdb restart
  tags: [ configure, influxdb ]

#- name: Set admin credentials
#  shell: influx -execute "CREATE USER admin WITH PASSWORD '{{ influxdb_admin_pass }}' WITH ALL PRIVILEGES"

- meta: flush_handlers

- name: Start influxdb
  systemd:
    name: influxdb
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [ install, influxdb ]

- name: Install Python Pip
  package:
    name: python3-pip
    state: present
- name: Install required Python modules
  pip:
    name:
    - requests
    - influxdb
- name: Set admin credentials
  influxdb_user:
    user_name: "admin"
    user_password: "{{ influxdb_admin_pass }}"
    state: present
    admin: yes
