---
- name: Add influxdb repo file
  copy:
    src: influxdb.repo
    dest: /etc/yum.repos.d
    owner: root
    group: root
    mode: 0644
  tags: [ install, influxdb ]

- name: Install influx
  package:
    name: influxdb
    enablerepo: influxdb
    state: present
  notify: influxdb restart
  tags: [ install, influxdb ]

- name: Copy influxdb config file
  template:
    src: influxdb.conf
    dest: /etc/influxdb/influxdb.conf
    owner: root
    group: root
    mode: 0644
  diff: yes
  notify: influxdb restart
  tags: [ configure, influxdb ]

- meta: flush_handlers

- name: Start influxdb
  systemd:
    name: influxdb
    state: started
    enabled: yes
    daemon_reload: yes
  tags: [ install, influxdb ]
- name: Install Python package manager
  package:
    name: python3-pip
    state: present
- name: Install Python modules
  pip:
    name:
    - requests
    - influxdb
- name: Set admin credentials
  influxdb_user:
    user_name: "{{influx_admin_username}}"
    user_password: "{{influx_admin_password}}"
    admin: yes
    state: present
- name: Set auth-enabled = true in influxdb.conf
  lineinfile:
    regexp: 'auth-enabled = false'
    line: 'auth-enabled = true'
    path: /etc/influxdb/influxdb.conf