---
- name: Install Midnight Commander
  apt:
    name: "mc"
    state: latest
- name: Create config directory
  file:
    path:  /root/.config/mc
    state: directory
#- name: Create MC config directory
#  file:
#    path:  /root/.config/mc
#    state: directory

- name: Create Confi File
  copy:
    content: ""
    dest: /root/.config/mc/ini
    force: yes
    group: sys
    owner: root
    mode: 0555

- name: Make Internal Editor Default
  lineinfile:
    path: /root/.config/mc/ini
    search_string: 'use_internal_edit=false'
    line: use_internal_edit=true
    owner: root
    group: root
    mode: '0644'