---
- name: "Create database {{ influx_database }}"
  influxdb_database:
    username: "{{ influx_admin_username }}"
    password: "{{ influx_admin_password }}"
    database_name: "{{ influx_database }}"
  run_once: true
  tags: [ install ]
- name: "Apply retention policy to {{ influx_database }}"
  influxdb_retention_policy:
    hostname: "{{ influx_host }}"
    database_name: "{{ influx_database }}"
    username: "{{ influx_admin_username }}"
    password: "{{ influx_admin_password }}"
    policy_name: "{{ influx_retention_policy_name }}"
    default: yes
    duration: "{{influx_retention_duration}}"
    replication: 1
  run_once: true
  tags: [ install ]
- name: "Create influxdb user {{ influx_user }}"
  influxdb_user:
    username: "{{ influx_admin_username }}"
    password: "{{ influx_admin_password }}"
    user_name: "{{ influx_user }}"
    user_password: "{{ influx_password }}"
    grants:
      - database: "{{ influx_database }}"
        privilege: 'ALL'
  run_once: true
  tags: [ install ]
- name: Create influxdb datasource in Grafana
  grafana_datasource:
    name: "{{inventory_hostname}}"
    grafana_url: "http://10.0.0.10:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    org_id: "1"
    ds_type: "influxdb"
    ds_url: "http://{{inventory_hostname}}:8086"
    database: "{{ influx_database }}"
    user: "admin"
    password: "admin"
    time_interval: ">10s"
    state: present
  tags: [ install ]
